name: Release

on:
  workflow_call:
    inputs:
      publish:
        description: Publish command to run, set to empty to skip this step
        required: false
        type: string
      build:
        description: Build command to run, set to empty to skip this step
        required: false
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup JS
        uses: byronogis/workflows/setup-js@v1
        with:
          checkout_fetch-depth: '0'

      - name: Generate GitHub Changelog
        run: nlx changelogen@latest gh release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: ${{ inputs.build != '' }}
        run: ${{ inputs.build }}

      - name: Publish
        if: ${{ inputs.publish != '' }}
        run: ${{ inputs.publish }}
