name: Unit Test

on:
  workflow_call:
    inputs:
      typecheck:
        description: Type check command to run, set to empty to skip this step
        required: false
        type: string
        default: nr typecheck

      lint:
        description: Lint command to run, set to empty to skip this step
        required: false
        type: string
        default: nr lint

      build:
        description: Build command to run, set to empty to skip this step
        required: false
        type: string
        default: nr build

      test:
        description: Test command to run, set to empty to skip this step
        required: false
        type: string
        default: nr test

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20, 22, 24, 25]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JS
        uses: byronogis/workflows/setup-js@v1
        with:
          runtime-version: ${{ matrix.node-version }}

      - name: Build
        if: ${{ inputs.build != '' }}
        run: ${{ inputs.build }}

      - name: Lint
        if: ${{ inputs.lint != '' }}
        run: ${{ inputs.lint }}
        continue-on-error: true

      - name: Type Check
        if: ${{ inputs.typecheck != '' }}
        run: ${{ inputs.typecheck }}
        continue-on-error: true

      - name: Test
        if: ${{ inputs.test != '' }}
        run: ${{ inputs.test }}
